CREATE TABLE IF NOT EXISTS {table_name} (
    id VARCHAR PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    pubkey VARCHAR NOT NULL,
    marginfi_group VARCHAR NOT NULL,
    mint VARCHAR NOT NULL,
    usd_price FLOAT NOT NULL,
    operational_state VARCHAR NOT NULL,
    asset_weight_maintenance FLOAT NOT NULL,
    liability_weight_maintenance FLOAT NOT NULL,
    asset_weight_initial FLOAT NOT NULL,
    liability_weight_initial FLOAT NOT NULL,
    deposit_limit_in_tokens FLOAT NOT NULL,
    borrow_limit_in_tokens FLOAT NOT NULL,
    deposit_limit_in_usd FLOAT NOT NULL,
    borrow_limit_in_usd FLOAT NOT NULL,
    lenders_count INTEGER NOT NULL,
    borrowers_count INTEGER NOT NULL,
    deposit_rate FLOAT NOT NULL,
    borrow_rate FLOAT NOT NULL,
    group_fee FLOAT NOT NULL,
    insurance_fee FLOAT NOT NULL,
    total_assets_in_tokens FLOAT NOT NULL,
    total_liabilities_in_tokens FLOAT NOT NULL,
    total_assets_in_usd FLOAT NOT NULL,
    total_liabilities_in_usd FLOAT NOT NULL,
    liquidity_vault_balance FLOAT NOT NULL,
    insurance_vault_balance FLOAT NOT NULL,
    fee_vault_balance FLOAT NOT NULL
);
